version: '3.8'
services:
  api:
    image: demo-docker-compose-api:latest
    ports:
      - "8080:3000"
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - my_custom_network

networks:
  my_custom_network:
    driver: overlay
